/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acenginecalculator;

import javax.swing.JOptionPane;

/**
 *
 * @author gpmag
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {

        super.setResizable(false);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRFrequencia = new javax.swing.JRadioButton();
        jRNumeroDePolos = new javax.swing.JRadioButton();
        jRRPM = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLResultado = new javax.swing.JLabel();
        jTV1 = new javax.swing.JTextField();
        jTV2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de Pólos:");

        jLabel2.setText("RPM:");

        jLabel3.setText("Calcular:");

        buttonGroup1.add(jRFrequencia);
        jRFrequencia.setSelected(true);
        jRFrequencia.setText("Frequêcia");
        jRFrequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRFrequenciaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRNumeroDePolos);
        jRNumeroDePolos.setText("Número de Pólos");
        jRNumeroDePolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRNumeroDePolosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRRPM);
        jRRPM.setText("RPM");
        jRRPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRRPMActionPerformed(evt);
            }
        });

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLResultado.setText("0");

        jMenu1.setText("Sobre");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Sobre o Programa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Sobre o Autor");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jRFrequencia)
                            .addComponent(jRNumeroDePolos)
                            .addComponent(jRRPM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jTV2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jTV1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(77, 77, 77)
                        .addComponent(jLResultado)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRFrequencia)
                    .addComponent(jTV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRNumeroDePolos)
                    .addComponent(jLabel2))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRRPM)
                    .addComponent(jTV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLResultado))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        JOptionPane.showMessageDialog(null, "Autor:\nGabriel Peres Magni\n\nVersão:\n1.0");

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        this.dispose();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        double sV1 = 0, sV2 = 0;
        boolean erro = false;
        /*
        f = frequência;
        p = número de pólos;
        n = rotações por minuto      
        
         */

        try {
            double lV1 = Double.parseDouble(jTV1.getText());
            sV1 = lV1;
            if (lV1 <= 0) {
                throw new ArithmeticException("");
            }
        } catch (NumberFormatException e1) {
            JOptionPane.showMessageDialog(null, "Digite apenas números");
            jTV1.requestFocus();
            erro = true;

        } catch (ArithmeticException e2) {
            JOptionPane.showMessageDialog(null, "Digite apenas número positivos");
            jTV1.requestFocus();
            erro = true;
        } catch (Exception e3) {
            JOptionPane.showMessageDialog(null, "Erro:\n" + e3);
        } finally {
            if (!erro) {
                try {
                    double lV2 = Double.parseDouble(jTV2.getText());
                    sV2 = lV2;
                    if (lV2 <= 0) {
                        throw new ArithmeticException("");
                    } else {
                        if (jRFrequencia.isSelected()) {
                            jLResultado.setText(String.valueOf(sV1 * sV2 / 120));
                        } else if (jRNumeroDePolos.isSelected()) {
                            jLResultado.setText(String.valueOf(120 * sV2 / sV1));
                        } else if (jRRPM.isSelected()) {
                            jLResultado.setText(String.valueOf(120 * sV1 / sV2));
                        } else {
                            JOptionPane.showMessageDialog(null, "???");
                        }
                    }
                } catch (NumberFormatException e1) {
                    JOptionPane.showMessageDialog(null, "Digite apenas números");
                    jTV2.requestFocus();
                } catch (ArithmeticException e2) {
                    JOptionPane.showMessageDialog(null, "Digite apenas número positivos");
                    jTV2.requestFocus();
                } catch (Exception e3) {
                    JOptionPane.showMessageDialog(null, "Erro:\n" + e3);
                } finally {

                }

            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRFrequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRFrequenciaActionPerformed

        jLabel1.setText("Número de Pólos:");
        jLabel2.setText("RPM:");
    }//GEN-LAST:event_jRFrequenciaActionPerformed

    private void jRNumeroDePolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRNumeroDePolosActionPerformed

        jLabel1.setText("Frequência:");
        jLabel2.setText("RPM:");

    }//GEN-LAST:event_jRNumeroDePolosActionPerformed

    private void jRRPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRRPMActionPerformed

        jLabel1.setText("Número de Pólos:");
        jLabel2.setText("Frequência:");

    }//GEN-LAST:event_jRRPMActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        JOptionPane.showMessageDialog(null, "Calcule a Frequência, Rotações por Minuto e Número de Pólos de um motor de corrente alternada com o seguinte cálculo:\n\nf = n * p / 120\n\nOnde:\nf = frequência\nn = RPM do motor\np = número de pólos");

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButton jRFrequencia;
    private javax.swing.JRadioButton jRNumeroDePolos;
    private javax.swing.JRadioButton jRRPM;
    private javax.swing.JTextField jTV1;
    private javax.swing.JTextField jTV2;
    // End of variables declaration//GEN-END:variables
}
